apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
  namespace: fraud-system
spec:
  selector:
    app: fraud-detection
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
